# Generated by Django 4.2 on 2023-04-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movieorder'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='order_movies',
            field=models.ManyToManyField(related_name='user_orders', through='movies.MovieOrder', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=127, unique=True),
        ),
    ]
