# Generated by Django 4.2 on 2023-04-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movieorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieorder',
            name='buyed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
